### ISSUE TITLE
Examples from README don't compile for iotaz

### ISSUE THREAD

**Issue by rintcius** [frees-io/iota#89]
I am trying out iota for scalaz, but getting compilation errors. 

To reproduce:
* Import `iotaz._` instead of `iota._` in `tut/README.md` (as indicated in the README)
* in `sbt`: `readme/tut`

Details:

<details>
<summary>git diff</summary>

```
iota (master)$ git diff modules
diff --git a/modules/readme/src/main/tut/README.md b/modules/readme/src/main/tut/README.md
index 0cec909..2f9c682 100644
--- a/modules/readme/src/main/tut/README.md
+++ b/modules/readme/src/main/tut/README.md
@@ -32,7 +32,7 @@ constant time access of the values. This syntax scales cleanly to
 support any number of disjunct types.

 ```tut:silent
-import iota._ // or iotaz._
+import iotaz._ // or iotaz._
 import TList.::
 import TListK.:::

@@ -229,4 +229,4 @@ Copyright (C) 2016-2017 47 Degrees. <http://47deg.com>

 [comment]: # (End Copyright)

-[free example]: modules/tests/src/test/scala/iotatests/FreeCopKTests.scala
\ No newline at end of file
+[free example]: modules/tests/src/test/scala/iotatests/FreeCopKTests.scala
```
</details>

<details>
<summary>output readme/tut</summary>

```
sbt:iota> readme/tut
[info] Running tut.TutMain /Users/rintcius/dev/iota/modules/readme/src/main/tut /Users/rintcius/dev/iota .*\.(md|markdown|txt|htm|html)
[tut] compiling: /Users/rintcius/dev/iota/modules/readme/src/main/tut/README.md
[tut] *** Error reported at /Users/rintcius/dev/iota/modules/readme/src/main/tut/README.md:98
<console>:25: error: value IntFoo is not a case class, nor does it have an unapply/unapplySeq member
         case IntFoo(int)       => s"int: $int"
              ^
<console>:26: error: value StringFoo is not a case class, nor does it have an unapply/unapplySeq member
         case StringFoo(string) => s"string: $string"
              ^
<console>:27: error: value DoubleFoo is not a case class, nor does it have an unapply/unapplySeq member
         case DoubleFoo(double) => s"double: $double"
              ^
[error] (run-main-2) tut.TutException: Tut execution failed.
[error] tut.TutException: Tut execution failed.
[error] 	at tut.TutMain$.$anonfun$runl$6(TutMain.scala:17)
[error] 	at tut.Zed$State.$anonfun$flatMap$1(Zed.scala:32)
[error] 	at tut.Zed$State.$anonfun$flatMap$1(Zed.scala:32)
[error] 	at tut.Zed$IOOps.unsafePerformIO(Zed.scala:99)
[error] 	at tut.TutMain$.main(TutMain.scala:8)
[error] 	at tut.TutMain.main(TutMain.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:89)
[error] 	at sbt.Run.run0(Run.scala:83)
[error] 	at sbt.Run.execute$1(Run.scala:61)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:73)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at tut.TutPlugin$.$anonfun$tutOne$1(TutPlugin.scala:149)
[error] 	at scala.util.Success.foreach(Try.scala:249)
[error] 	at tut.TutPlugin$.tutOne(TutPlugin.scala:149)
[error] 	at tut.TutPlugin$.$anonfun$projectSettings$19(TutPlugin.scala:72)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
```
</details>

**Comment by andyscott** [comment]
Thanks! I am going to spend some time over this next week to address a few issues with the new features.

**Comment by andyscott** [comment]
I'm fairly sure this was solved by the already merged https://github.com/frees-io/iota/pull/80. I'm checking now, and will cut a release with a fix soon.

**Comment by rintcius** [comment]
Hmm, I tested it on `master` with that PR already in. 

Note that what's shown in the `git diff` output is the only thing I changed. Maybe I should have changed more (although I couldn't find it in the code)?

**Comment by andyscott** [comment]
I should have given you another update. There's definitely an issue! Looking to have this fixed ASAP.

**Comment by rintcius** [comment]
No problem @andyscott - thanks for looking into this!

**Comment by andyscott** [comment]
See https://github.com/frees-io/iota/pull/94 for an update.

**Comment by andyscott** [comment]
@rintcius The readme examples are split should work now for v0.3.3.

**Comment by rintcius** [comment]
great, thanks @andyscott !
